### PR TITLE
fix #13 : reorder/transpose array via drag & drop on filter labels

### LINKED ISSUE #13: reorder/transpose array via drag & drop dimension names
https://github.com/liam2/larray/issues/140

### PR DESCRIPTION
**Pull request by alixdamman**
Wait for PR #26 and that I put test package on larray-test conda channel before to merge. 
In the meantime, ready for review

### CODE REVIEW

**Comment by alixdamman** [comment]
Well, that will need to add an entry in the changelog of larray (once merged).

**Comment by alixdamman** [comment]
Did you test it?

**Comment by gdementen** [comment]
yes, otherwise I wouldn't comment on its usage... Why do you ask?

**Comment by alixdamman** [comment]
I was not sure that the transpose was propagated to the MappingEditor.

**Pull request merged**
