### PR TITLE
Revert "updated setup.py --> removed pyqt and qtpy"

### PR DESCRIPTION
**Pull request by alixdamman**

### CODE REVIEW

**Comment by gdementen** [comment]
based on #7, I understand the `python setup.py install` does not work with them, so why included them now?

**Comment by alixdamman** [comment]
See PR https://github.com/liam2/larray/pull/379 from project larray.

**Comment by alixdamman** [comment]
Close this PR because pyqt cannot be installed via pypi. Sorry.

**Comment by gdementen** [comment]
add an explicit note about this in setup.py so that we do not try to do this again in the future?

**Pull request closed without merging**
