### PR TITLE
(issue 178) : import Product class from larray

### PR DESCRIPTION
**Pull request by alixdamman**

### CODE REVIEW

**Comment by alixdamman** [comment]
@gdementen OK with the 3 last commits ?

**Comment by gdementen** [comment]
no 😄. 
* both "dist: xenial" and "sudo: true" are the default now (https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration), so I think python 3.7 should be added like the other python versions.
* now that pytables 3.5 is released, the numpy != 1.16 restriction should be removed from larray instead of being added to larray-editor, so that our users can actually update larray

**Comment by alixdamman** [comment]
FWIW, pytables 3.5 is not available for Python 3.5

**Comment by gdementen** [comment]
then I guess we should drop support for python 3.5. That's better than having larray not being installable :)

**Comment by alixdamman** [comment]
Now the question is: do you we have users still stuck with Python 3.5?

**Comment by gdementen** [comment]
Yes, we have a few, but they can stay with larray 0.30 until the iode module is recompiled for python 3.6+. Currently larray 0.30 is not installable (even explicity!) for several of our users.

**Comment by alixdamman** [comment]
OK to merge?

**Comment by gdementen** [comment]
the PR itself LGTM but on a related note "dist: xenial" should be added in travis.yml so that we don't get "random" failures for python 3.7

**Pull request merged**
