### PR TITLE
fix #115: added make_release.py and next_release.py scripts

### LINKED ISSUE #115: create make_relase script

### PR DESCRIPTION
**Pull request by alixdamman**

### CODE REVIEW

**Comment by gdementen** [comment]
Instead of duplication those functions over and over, I would rather move most of these functions to a new project that all our projects would depend on. eg. larray-project/releaser

**Comment by alixdamman** [comment]
Why not in the future new project `larrayenv`? 
Or do you prefer to create a specific project only responsible to manage the releases?

**Comment by gdementen** [comment]
I prefer the second option because otherwise we have cyclic dependencies: larray depends on larrayenv and larrayenv depends on larray. Besides LIAM2 will not be part of larrayenv.

**Comment by gdementen** [comment]
this PR needs to be updated to use the releaser lib

**Pull request merged**
